version: '3.3'

services:
      
  # init_prometheus:
  #   image: prom/prometheus:v2.37.7
  #   user: root
  #   entrypoint:
  #     - /bin/sh
  #     - -c
  #     - |
  #       chown -R 65534:65534 /prometheus
  #   volumes:
  #     - /volume3/container/smartie2/prometheus/data/prometheus:/prometheus
      
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   restart: always
  #   links:
  #     - nats
  #     - smartie
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - /volume3/container/smartie2/prometheus/configs/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - /volume3/container/smartie2/prometheus/data/prometheus:/prometheus
  #     - /volume3/container/smartie2/prometheus/file_sd:/etc/prometheus/file_sd


  smartie:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smartie
    restart: always
    # links:
    #   - nats
    ports:
      - "2112:2112"

  # nats:
  #   image: nats:latest
  #   container_name: nats
  #   command:
  #     - -c
  #     - /etc/nats/server.conf
  #   volumes:
  #     - /volume3/container/smartie/nats/server.conf:/etc/nats/server.conf
  #   restart: always
  #   ports:
  #     - "4222:4222"
  #     - "1883:1883"